language: "node_js"
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "5"
  - "6"

before_install:
 - "npm install istanbul -g"
 - "npm install coveralls -g"

script: "make ci-travis"

after_success:
  - "make submit-cov-to-coveralls"
